# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JibSpaceX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JibSpaceX
  pod "Alamofire"
  pod "ImageSlideshow/SDWebImage"
  pod "RxSwift"
  pod "ObjectMapper"

  target 'JibSpaceXTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
